/**
 * Generates the Move source for a per-vault share token package.
 * One OTW SHARE type -> one TreasuryCap, handed to the deployer to pass into
 * floe::deploy_vault as the vault's share Coin S. Uses the modern
 * coin_registry::new_currency_with_otw API (verified live on testnet).
 */

export interface ShareModuleOpts {
  symbol: string;        // e.g. "flStratos"
  name: string;          // e.g. "Floe Stratos Share"
  description?: string;
  decimals?: number;     // default 6 (match quote asset)
}

export interface GeneratedShareModule {
  packageName: string;   // unique per vault, e.g. "floe_share_a1b2c3d4"
  moduleName: string;    // "share"
  otwName: string;       // "SHARE"
  moveToml: string;
  shareMove: string;
}

/** Deterministic-ish unique suffix so two vaults never collide in a local build dir. */
function uniqueSuffix(): string {
  return Math.random().toString(16).slice(2, 10);
}

export function generateShareModule(opts: ShareModuleOpts): GeneratedShareModule {
  const decimals = opts.decimals ?? 6;
  const description = opts.description ?? 'Floe vault share';
  const pkg = `floe_share_${uniqueSuffix()}`;

  const moveToml = `[package]
name = "${pkg}"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
${pkg} = "0x0"
`;

  // Modern coin_registry path. Arg order (verified vs Mysten source):
  // new_currency_with_otw(otw, decimals, SYMBOL, NAME, DESCRIPTION, ICON_URL, ctx)
  //   -> (CurrencyInitializer, TreasuryCap); builder.finalize(ctx) -> MetadataCap.
  const shareMove = `/// Per-vault Floe share token. Generated by @floe/sdk.
/// OTW SHARE -> TreasuryCap handed to deployer for floe::deploy_vault.
module ${pkg}::share;

use sui::coin_registry;

public struct SHARE has drop {}

fun init(otw: SHARE, ctx: &mut TxContext) {
    let (builder, treasury_cap) = coin_registry::new_currency_with_otw(
        otw,
        ${decimals},
        b"${opts.symbol}".to_string(),
        b"${opts.name}".to_string(),
        b"${description}".to_string(),
        b"".to_string(),
        ctx,
    );
    let metadata_cap = builder.finalize(ctx);
    transfer::public_transfer(treasury_cap, ctx.sender());
    transfer::public_transfer(metadata_cap, ctx.sender());
}
`;

  return { packageName: pkg, moduleName: 'share', otwName: 'SHARE', moveToml, shareMove };
}
